[package]
name = "twitter_archiver"
version = "0.1.0"
authors = ["Evan Chang <evanc577@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33"
futures = "0.3"
fs_extra = "1.2"
itertools = "0.10"
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempdir = "0.3"
tokio = { version = "1.9", features = ["full"] }
toml = "0.5"
unicode-segmentation = "1.8"
url = "2.2"
